#!/usr/bin/env bash

rm -rf $GOPATH/src/github.com/lib
#rm -rf $GOROOT/src/github.com/lib
cp -rf lib $GOPATH/src/github.com/lib
#cp -rf lib $GOROOT/github.com/src/

echo "actions_chaincode"
cd actions_chaincode
go build
cd ..
echo "commodities_chaincode"
cd commodities_chaincode
go build
cd ..
echo "companies_chaincode"
cd companies_chaincode
go build
cd ..
echo "delivery_vouchers_chaincode"
cd delivery_vouchers_chaincode
go build
cd ..
echo "locations_chaincode"
cd locations_chaincode
go build
cd ..
echo "lots_chaincode"
cd lots_chaincode
go build
cd ..
echo "order_transportations_chaincode"
cd order_transportations_chaincode
go build
cd ..
echo "order_warehouses_chaincode"
cd order_warehouses_chaincode
go build
cd ..
echo "pick_lists_chaincode"
cd pick_lists_chaincode
go build
cd ..
echo "preorders_chaincode"
cd preorders_chaincode
go build
cd ..
echo "products_chaincode"
cd products_chaincode
go build
cd ..
echo "storages_chaincode"
cd storages_chaincode
go build
cd ..
echo "transportation_logs_chaincode"
cd transportation_logs_chaincode
go build
cd ..
echo "transportations_chaincode"
cd transportations_chaincode
go build
cd ..
echo "truck_makes_chaincode"
cd truck_makes_chaincode
go build
cd ..
echo "truck_models_chaincode"
cd truck_models_chaincode
go build
cd ..
echo "trucks_chaincode"
cd trucks_chaincode
go build
cd ..
echo "users_chaincode"
cd users_chaincode
go build
cd ..
echo "warehouses_chaincode"
cd warehouses_chaincode
go build
cd ..